### ISSUE TITLE
Hanging on "Waiting for pioneerAvrAccessory to be ready"

### ISSUE THREAD

**Issue by cdm94** [kazcangi/homebridge-pioneer-avr#15]
[5/20/2020, 7:01:57 PM] [Receiver Apple TV] Waiting for pioneerAvrAccessory to be ready
[5/20/2020, 7:01:57 PM] [Receiver Apple TV] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
    at Function.module.exports.loopWhile (/usr/local/lib/node_modules/homebridge-pioneer-avr/node_modules/deasync/index.js:71:23)
    at Function.sleep (/usr/local/lib/node_modules/homebridge-pioneer-avr/node_modules/deasync/index.js:41:18)
    at pioneerAvrAccessory.getServices (/usr/local/lib/node_modules/homebridge-pioneer-avr/index.js:317:28)
    at Server.createHAPAccessory (/usr/local/lib/node_modules/homebridge/src/server.ts:441:41)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:359:30
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:329:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:155:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by kazcangi** [comment]
Hi
Can you enable Network Standby option in configuration tion menu of your AVR?
If this option is enabled, try to power cycle your AVR. The telnet server included in AVR allow only one connection at a time. If a connection is not cleanly closed, power cycling solves the problem

**Comment by cdm94** [comment]
Hello I already had network standby on, I also have tried the power cycling. 

The only thing that I could do to get it to work for a while was to disable some of the input options in the code of the plugin itself and even then it still would crash my Homebridge server after a few mins.
