### ISSUE TITLE
VSX-921-K

### ISSUE THREAD

**Issue by xEzeit** [kazcangi/homebridge-pioneer-avr#17]
Hi, I'm running into an issue when I'm using the plugin with my Pioneer VSX-921-k amplifier. Homebridge is unable to start and gives me the following error:

[8/15/2020, 12:50:07 PM] [My Pioneer AVR] Get power status
[8/15/2020, 12:50:07 PM] [My Pioneer AVR] Get mute status
[8/15/2020, 12:50:07 PM] [My Pioneer AVR] Get volume status
[8/15/2020, 12:50:07 PM] TypeError: this.volumeStatus is not a function
    at pioneerAvrAccessory.getVolume (/usr/lib/node_modules/homebridge-pioneer-avr/index.js:254:10)
    at Volume.emit (events.js:310:20)
    at Volume.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Volume.Characteristic._this.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:489:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1215:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1143:10)
    at HAPServer.emit (events.js:310:20)
    at HAPServer.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:756:12)
[8/15/2020, 12:50:08 PM] Got SIGTERM, shutting down Homebridge...
Error: connect ECONNREFUSED 192.168.63.110:51656

If you need anymore informations about my setup I'm here
Thanks

**Comment by doppelff** [comment]
Hey,
i have install the plugin today and get the same error with my vsx922.
I update line 254 at /usr/local/lib/node_modules/homebridge-pioneer-avr/index.js 
from
`this.volumeStatus(callback);`
to
`this.avr.volumeStatus(callback);`

This works for me.
